project:
  type: website
  output-dir: docs

website:
  title: "Home"
  description:
  site-url: "https://tiffany-ngli.github.io/authors-royalty-website/"
  navbar:
    background: primary
    search: false
    
format:
  html:
    theme: Litera
    toc: false

editor:
  mode: source